version: "3"

services:
  app:
    image: docker.io/ossuchas/djangotest:v1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
